#!/bin/bash

cd /autograder/source/sample-server

node index.js &

sleep 5

cd /autograder/submission

# temporary testing
curl -X GET http://localhost:3000

bash /autograder/source/run_tests.sh

# Upload test results to database, and return for gradescope

mv results.json /autograder/results
